//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageSchoolProjectAuto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carfavs
    {
        public int ID { get; set; }
        public string Kenteken { get; set; }
        public string Merk { get; set; }
        public string Handelsbenaming { get; set; }
        public string Inrichting { get; set; }
        public string EUcat { get; set; }
        public Nullable<int> AantalCilinders { get; set; }
        public Nullable<int> Wielbasis { get; set; }
        public string carSearch { get; set; }
    }
}
